version: '3.5'

services:
  postgres:
    image: postgres:13
    container_name: 'postgres-vtt-connector'
    ports:
      - "5439:5432"
    env_file:
      - ./VTT_connector/postgres.env
    networks:
      - connector
    volumes:
      - /opt/docker/postgresql-data:/var/lib/postgresql/data

  connector:
    build:
      context: ./VTT_connector/.
    container_name: 'vtt-connector'
    ports:
      - 8081:8081
    env_file:
      - ./VTT_connector/connector.env
    networks:
      - connector
    depends_on:
      - postgres

  ui:
    build:
      context: ./VTT_ui/.
    environment:
      - CONNECTOR_URL=https://localhost:8081
      - CONNECTOR_USER=admin
      - CONNECTOR_PASSWORD=password
    ports:
      - "8083:8083"
    depends_on:
      - connector


networks:
  connector: