version: '3.5'

services:
    ui:
        build:
            context: .
        environment:
        - CONNECTOR_URL=https://localhost:8081
        - CONNECTOR_USER=admin
        - CONNECTOR_PASSWORD=password
        ports:
        - "8083:8083"
        depends_on:
        - connector
