name: Publish Docker image

on:
  push:
    branches:
      - hack

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: RyanKelvinFord
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./VTT_connector/Dockerfile
          push: true
          tags: ghcr.io/advanced-dataspaces-vtt/vtt-example-ids-connector/dataspaceconnector-development:latest